"LR": 3e-4
"NUM_ENVS": 2048
"NUM_STEPS": 10
"TOTAL_TIMESTEPS": 5e7
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 32
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"ENT_COEF": 0.0
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "relu"
"ENV_NAME": "hopper"
"ANNEAL_LR": False
"NORMALIZE_ENV": True
"DEBUG": True
"ENTITY": "oxwhirl"
"PROJECT": "rl-nn-dynamics"
"SEED": 0
"WANDB_MODE": "disabled"
"TAU": 0.0
"DISABLE_JIT": False
"OPTIMIZER": "adam"
"B1": 0.9
"B2": 0.999